# Numpy

- https://numpy.org/devdocs/user/whatisnumpy.html
- https://numpy.org/devdocs/user/quickstart.html#stacking-together-different-arrays

* [Basic Concepts](#Basic-Concepts)
* [Basic Operations](#Basic-Operations)
  * [Creating ndarrays](#Creating-ndarrays:)
  * [Most used ndarray properties](#Most-used-ndarray-properties:)
  * [Indexing & Slicing ndarrays](#Indexing-&-Slicing-ndarrays:)
  * [Iterating ndarrays](#Iterating-ndarrays:)
  * [Reshaping ndarrays](#Reshaping-ndarrays:)
  * [Views and copies of ndarrays](#Views-and-copies-of-ndarrays:)
  * [Splitting and stacking ndarrays](#Splitting-and-stacking-ndarrays:)
* [Basic Functions](#Basic-Functions)

In [0]:
# try to be Python 3 compatible
from __future__ import division, print_function

# pretty printer
import pprint
pp = pprint.PrettyPrinter(indent=2).pprint

In [0]:
import numpy as np
from numpy import dot

## Numpy options for Jupyter usage

In [0]:
# set floats print width (number of decimals)
np.set_printoptions(precision=4)
# set floats print width and show as zeroes numbers too small to display
# (otherwise they'd get displayed using scientific notation)
# np.set_printoptions(precision=4, suppress=True, linewidth=100)

## Basic Concepts

* Core datatype [ndarray](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html): n-dimensional array, homegenous, of fixed-size items.
* Universal functions - they can work on both numbers and arrays (when called with lists they get converted to arrays)
  * Most of them get applied to each element of an array when called with arrays.
  * Basic operators like `+`, `*`, `<` etc. behave the same way. (Note that `*` is also applied elementwise (unlike in Matlab) and [`np.dot`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) is used for matrix multiplications
  * Operators like `+=` or `*=` modify in place an existing array
* Equivalent methods for the universal functions - whether to use the function version (eg. `np.dot(A, B)`) or the method version (eg. `A.dot(B)`) is a question of style/preference

## Basic Operations

### Creating ndarrays:

* from lists and/or tuples:
  * `np.array([[1,2,3],(4,5,6)]) #=> 2x3 2D ndaray`
  * `np.array([1,2,3]) #=> size 3 1D ndarray`
* zeros - *np.zeros(size_tuple[, dtype])* : `np.zeros( (3,4) )`
* ones - *np.ones(size_tuple[, dtype])* : `np.ones( (2,3,4), dtype=np.int16 )`
* range - *arange* is like range but works with ndarrays and supports things like float steps and more:
  * `np.arange(1, 3, 0.5) #=> array([1.0,1.5,2.0,2.5])`
* [linspace](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html) - use instead of arange when you care about the numebr of points and not the step size:
  * `np.linspace(0, 3, 5) #=> array([0.0,0.75,1.5,2.25,3.0])`
* reshape:
  * `np.linspace(0, 3, 6).reshape( (2,3) ) #=> array([[ 0. ,  0.6,  1.2], [ 1.8,  2.4,  3. ]])`
* random ( *np.random.random([size])* or *np.random.normal(mu, sigma, size)* ) :
  * `np.random.random((2,3))`
* from function of element indices:
  * `np.fromfunction(lambda x, y: x*10+y, (2,3), dtype=int) #=> array([[ 0,  1,  2], [10, 11, 12]])`



### Most used ndarray properties:

* `.shape` - dimensions, eg.:
  * `np.array([1,2,3]).shape == (3,)` - vector of 3 elements (1D vector)
  * `np.array([[1,2,3]]).shape == (1,3)` - 1 row 3 cols matrix (2D "row vector" in Matlab/Octave)
  * `np.array([[1],[2],[3]]).shape == (3,1)` - 3 rows 1 col matrix (2D "column vector" in Matlab/Octave)
  * `np.array([[11,12,13],[21,22,23]]).shape == (2,3)` - 2 rows 3 cols matrix
* `.ndim` - number of dimensions (axes), also called *rank* (`a.ndim == len(a.shape)`)
* `.size` - total no. of elements
* `.dtype` - type of elements (all elements must be of the same type)
* `.itemsize` - size in bytes an array element (alias of `.dtype.itemsize`)
* `.data` - actual buffer (rarely touched directly!)

**NOTE:** having "true 1D" vectors instead of messing around with row-vector and column-vectors is nice, but it's important to remember that when we multiply a matrix (2D) with a vector (1D) (eg. `np.dot(m, v)`), the vector gets treated as 1-column matrix and then the rules matrix multiplication are applied. Also, when 2 vectors are multiplied, what gets computed is the dot product (equivalent with multiplying a 1-row matrix with a 1-column matrix). Anyway, just **make sure you understant what [`numpy.dot`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) does in all cases!**

###  Indexing & Slicing ndarrays:

* 1D - just like Python lists
* nD - one index per axis eg.:
  * `a[2,3]` - element at line 2 col 2
  * `a[0:5,1]` - slice of rows 0 to 5 and column 1
  * `a[:,2]` - all rows column 2
  * `a[-1]` equiv. `a[-1,:]` - last row all columns
  * **NOTE 1:** avoid using expressions like `a[0][2]` instead of `a[0,2]`, because the first one creates a temporary array for row 0 which is then indexed by 2.
  * **NOTE 2:** slices do not copy data but represent views into the same array, so modifying data in a slice modifies it in the original array too! (use `np.copy(m[0:3, 1:2])` to copy a slice as an independent array if this is what you need)
* by another array of indexes: see [docs](https://docs.scipy.org/doc/numpy-dev/user/basics.indexing.html#index-arrays); returns a copy of data, not a view like slices; also works with lists, but not with tuples
  * `np.arange(1,6)[[3,1,1]] #=> array([4, 2, 2])`
* by boolean or “mask” index arrays: [works as expected](https://docs.scipy.org/doc/numpy-dev/user/basics.indexing.html#boolean-or-mask-index-arrays); also returns a copy of data like indexing by another array, not a view like slices
  * `np.arange(1, 6)[np.array([False, True, True, False, True])] #=> array([2, 3, 5])`

### Iterating ndarrays:

Is done with respect to first axis: `for row in a: ...`.

Alternative is to use `.flat` to go over each element: `for element in a.flat: ...`

### Reshaping ndarrays:

In [0]:
# flattening N-D to 1-D
m = np.array([[1, 3], [2, 4]])
pp(m)
pp(m.ravel())
pp(m) # original matrix not changed

array([[1, 3],
       [2, 4]])
array([1, 3, 2, 4])
array([[1, 3],
       [2, 4]])


In [0]:
# starting with 1D vector,
# create new col vector in 2 ways
v = np.arange(3)
pp(v)
pp(v.reshape(3, 1))
pp(v[:, np.newaxis]) # creates a view (and same as v[:, None])
pp(v.reshape(-1, 1)) # -1 means "whatever is needed"

array([0, 1, 2])
array([[0],
       [1],
       [2]])
array([[0],
       [1],
       [2]])
array([[0],
       [1],
       [2]])


In [0]:
# change shape of existing array
v = np.arange(3)
pp(v)
v.shape = (3, 1) # same as calling .resize(...)
pp(v)
v.resize((1, 3)) # same as assigning to .shape
pp(v)

array([0, 1, 2])
array([[0],
       [1],
       [2]])
array([[0, 1, 2]])


**IMPORTANT:** In all examples above, we only get new views of the same data, so modifying an element in one modifies it in all others too.

**Note:** changing the *shape* of a view does not change other linked arrays (only changing data in it does), so the shape is actually unique to each view, as opposed to the data.

### Views and copies of ndarrays:

* `.view()` - creates a new array object that looks at the same data
* `.copy()` - creates a new array with a new clone of the data

### Stacking arrays
See https://numpy.org/devdocs/user/quickstart.html#stacking-together-different-arrays
* [np.hstack](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.hstack.html#numpy.hstack) - stacks along 2nd axis
* [np.c_](https://numpy.org/devdocs/reference/generated/numpy.c_.html#numpy.c_) - as above, but nice because it also works with ranges
* [np.vstack](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.vstack.html#numpy.vstack) - stacks along 1st axis
+ [np.r_](https://numpy.org/devdocs/reference/generated/numpy.r_.html#numpy.r_) - similar to above, also supports ranges
* [np.dstack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dstack.html?highlight=dstack#numpy.dstack) - stack along 3rd (depth) dimension
* [np.column_stack](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.column_stack.html#numpy.column_stack) - stack 1-D vectors as columns
* `np.row_stack` - same as `vstack` (maybe it's clearer to use this instead of `vstack` when stacking 1-D arrays as rows)
* [np.concatenate](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.concatenate.html#numpy.concatenate) - most general concatenation function, cat do what all the above do
* [np.block](https://docs.scipy.org/doc/numpy/reference/generated/numpy.block.html#numpy.block) - assemble an nd-array from nested lists of blocks (probably most general of all)

In [0]:
a = np.array([[1, 2], [3, 4]])
print("a:"); pp(a)
b = np.array([[10, 20], [101, 202]])
print("b:"); pp(b)
v1 = np.array([5, 6])
print("v1:", v1)
v2 = np.array([700, 800])
print("v2:", v2)

a:
array([[1, 2],
       [3, 4]])
b:
array([[ 10,  20],
       [101, 202]])
v1: [5 6]
v2: [700 800]


In [0]:
np.hstack((a, b))
# same: np.concatenate((a, b), axis=1)
# same: np.c_[a, b]

array([[  1,   2,  10,  20],
       [  3,   4, 101, 202]])

In [0]:
np.c_[1:5, 101:105]

array([[  1, 101],
       [  2, 102],
       [  3, 103],
       [  4, 104]])

In [0]:
np.vstack((a, b))
# same: np.concatenate((a, b), 0)
# same: np.r_[a, b]

array([[  1,   2],
       [  3,   4],
       [ 10,  20],
       [101, 202]])

In [0]:
np.r_[1:5, 101:105]

array([  1,   2,   3,   4, 101, 102, 103, 104])

In [0]:
np.column_stack((v1, v2))  # concat 1-D vectors as columns

array([[  5, 700],
       [  6, 800]])

In [0]:
# !! very different from above (1-D vectors treated as row-matrixes)
np.hstack((v1, v2))

array([  5,   6, 700, 800])

In [0]:
np.column_stack is np.hstack

False

In [0]:
np.row_stack((v1, v2))

array([[  5,   6],
       [700, 800]])

In [0]:
# same as above (1-D vectors treated as row-matrixes)
np.vstack((v1, v2))

array([[  5,   6],
       [700, 800]])

In [0]:
np.row_stack is np.vstack

True

In [0]:
np.dstack((a, b))
# same as: np.concatenate((a[:, :, None], b[:, :, None]), 2)

array([[[  1,  10],
        [  2,  20]],

       [[  3, 101],
        [  4, 202]]])

In [0]:
A = np.eye(2) * 2
B = np.eye(3) * 3
np.block([
    [A,               np.zeros((2, 3))],
    [np.ones((3, 2)), B               ]
])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

### Splitting arrays

* [np.hsplit](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.hsplit.html#numpy.hsplit) splits along 2nd dim., second arg. is number of splits or list of splits indices
* [np.vsplit](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.vsplit.html#numpy.vsplit) - splits along 1st dim. similar to `hsplit`
* [np.dsplit](https://numpy.org/devdocs/reference/generated/numpy.dsplit.html#numpy.dsplit) - as above, but on depth (3rd) dimension
* [np.split](https://numpy.org/devdocs/reference/generated/numpy.split.html#numpy.split) - most general, takes a 3rd arg. specifying the axis
* [np.array_split](https://numpy.org/devdocs/reference/generated/numpy.array_split.html#numpy.array_split) - like `split`, but does not throw error when number of sections does not divide the axis evenly

In [0]:
ab = np.hstack((a, b))
pp(ab)
print("--- hsplit(ab, 2):")
# same: for m in np.split(ab, 2, axis=1):
for m in np.hsplit(ab, 2):
    pp(m)
print("--- hsplit(ab, [3]):")
# same: for m in np.split(ab, [3], 1):
for m in np.hsplit(ab, [3]):
    pp(m)
print("--- array_split(ab, 3, axis=1):")
# doesn't work: np.hsplit(ab, 3)
# doesn't work: np.split(ab, 3, 1)
for m in np.array_split(ab, 3, axis=1):
    pp(m)

array([[  1,   2,  10,  20],
       [  3,   4, 101, 202]])
--- hsplit(ab, 2):
array([[1, 2],
       [3, 4]])
array([[ 10,  20],
       [101, 202]])
--- hsplit(ab, [3]):
array([[  1,   2,  10],
       [  3,   4, 101]])
array([[ 20],
       [202]])
--- array_split(ab, 3, axis=1):
array([[1, 2],
       [3, 4]])
array([[ 10],
       [101]])
array([[ 20],
       [202]])


## Basic Functions

In [0]:
a = np.random.random(10) * 10
pp(a)

array([2.25999771, 2.06195198, 0.46153114, 1.0398915 , 2.70391965,
       8.23455529, 8.24491328, 2.30260736, 8.05771462, 3.60579353])


In [0]:
print("max:", np.max(a), ", min:", np.min(a))

max: 8.244913282292185 , min: 0.4615311356520313


In [0]:
print("mean:", np.mean(a), a.mean())

mean: 3.8972876047763 3.8972876047763


In [0]:
print("median:", np.median(a))

median: 2.503263504141066


In [0]:
print("variance:", np.var(a))

variance: 8.509330393246604


In [0]:
print("sum:", np.sum(a))

sum: 38.972876047763


## Broadcasting

**Read this thoroughly:** https://docs.scipy.org/doc/numpy/user/theory.broadcasting.html#array-broadcasting-in-numpy

In [0]:
A = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
Acol = np.array([0.0, 10.0, 20.0, 30.0]).reshape(-1, 1)
Bvec = np.array([1.0, 2.0, 3.0])
Brow = np.array([[1.0, 2.0, 3.0]])

In [0]:
A + Brow

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [0]:
A + Bvec

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [0]:
Acol + Bvec

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [0]:
Acol + Brow

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

## Vector and Matrix Multiplication

- [np.dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)
  - this does very different things in different situations (pay attention to the docs), so it's better to use this **only for actual/mathematical "dot product" aka. "scalar product" aka. "inner product"** and use something more specific instead for the other case (see the ones below)
- [np.matmul](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul) or the `@` operator, actual **matrix multiplication** for 2D arrays, with the following behavior if one of them is 1D (see docs for behavior in multiple dimensions):
    - `1D-vector @ 2D-matrix` = `2D-row-matrix @ 2D-matrix` - "If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed."
    - `1D-vector @ 2D-matrix` = `2D-row-matrix @ 2D-matrix` - "If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed."

In [0]:
m = np.array([[5, 15], [100, 200]]); m

array([[  5,  15],
       [100, 200]])

In [0]:
display(np.array([2, 10]) @ m)
display(np.matmul(np.array([2, 10]), m))
display(np.dot(np.array([2, 10]), m))
display(np.array([[2, 10]]) @ m)

array([1010, 2030])

array([1010, 2030])

array([1010, 2030])

array([[1010, 2030]])

In [0]:
display(m @ [2, 10])
display(m @ np.array([[2], [10]]))

array([ 160, 2200])

array([[ 160],
       [2200]])

## Optimizations - output to variable

Operations like `np.matmul` support an optional `out` parameter specifying and exisitng array (of the right shape) where the result will be stored. This prevents a costly memory allocation, so it helps a lot when repeatedly multilying large matrices and only caring about the last result.

In [0]:
print("a:"); display(a)
print("b:"); display(b)

a:


array([[1, 2],
       [3, 4]])

b:


array([[ 10,  20],
       [101, 202]])

In [0]:
# same: a @ b
np.matmul(a, b)

array([[212, 424],
       [434, 868]])

In [0]:
c = np.zeros((2,2), dtype=int); c

array([[0, 0],
       [0, 0]])

In [0]:
np.matmul(a, b, out=c)

array([[212, 424],
       [434, 868]])

In [0]:
c

array([[212, 424],
       [434, 868]])